sudo: required
language: cpp
services:
- docker
cache:
  directories:
  - "$CACHE_DIR"
env:
  global:
  - CACHE_DIR=$HOME/.cache/docker
  - CACHE_FILE_YAEL=$CACHE_DIR/yael
  - secure: Zz02UVYOIfQds+YDtSE7YmD7EUhkHrLZsj0wc13HhVmr1gZZlUFEx+16PmO7Z0GsO8NBzn251l3ErZrdPoMZh20w2rMc1g+kLc2XjNtk8VE5yfOXeSeAX4Ct6IP9j9HN+I8uaMx0vKlz6/0DhIY1U/70+g3UL8GfCTDujBa9DpfSV0mB3lj+Isir8Ybpw5LFTgqh6Ri5IAxB578FJRqxHZq0wy5cBYPy6iGmBNsU304TzqZeu667Z1HFjYUleN25K05Cinf+qrh/LWE9d+WVDc5YnSgIsSQ2NlBCVQPeoW/wpP2MEg1hw14fMENggiQvJz81ggyCYrF9yQXJLwwxhSEdpgUplEd95iORE9dILSoXuH52Le5MGdA08DyTOK3r6PHdoFmWye+i/01hjzJfbu6tedwEpDcHu31LaJkRO5jluOMkx/6X4Le6Thl4BGsqNgLTZT2TqK+znGi8OPI8/FaY+9OaaYjT1/PYohbliXeCO2/uTVeEY9ej45doAe6CmIMBJn3+BHxr7Ag6PVUTW8hFgFy3FEYCHOzCBY1PaC3M7Knl2mdUjkhy5naX2RqQ4aKA9kQzcotQIQm/NRmh3ouHWDwqbDVuhUNPsc/YfkOGEzovUcGiAorINSVcFFWaC9W/ywYrol1aHI0KGoY5Y3kTge1XN6I/77+YPLJJiaU=
  - secure: UA6vLhWZJaCafNrQZ09vNBqHHUwhZM+bCXRwDHlcDL1eSG9uxdSPmHfzVdgfXjcKuzGtSx9sYRZwv9toVtBIzUGHYsQjC8Z/8u2ps32X0kyqhu4KCeaFnlH3uc0y84AkBPThOP2wUrgOy2ABO9zvdLE5OLSpFS/mkq92W36amBK2n+QIfh3XCzGaqeh930ue/C1dz/5n8C1U4xOn6gjJKY+F1MY3huk3j6N5eCXMDXvthWGeXiAH6+nJndE5WIWL8J9CB7AvKaEvap2f9tLVILTBMvXV08t8z0YCD18y5eDchOglSqinU9Jf2kFQi2SffG2f8cJ/XIo2l6ZqNVfhOvLMsbNCvNX0LlasT95bn0Fs6tdEZ6EyMID+vzI7MyBjBcJsNLKcQ3CMRkFoKtuMtIbxDbx7vkRlMCG44v6b8NMsZx8CbVo9epfIpQbs/64KYfBU1JrRfN0FO6GXzIh+ip99oYBfFzUhA1TnSG3qoPwyMlE3YG7mgy6pDvXBzXd3FgFaFk3qNyXpDqwQnz4PCuIN8PDh90DoPOQ8FbvO42yY4ZCufw7c2tJL8Cm//CXamYOQk+rGHaFLuTOF7Csvzy99DIVP+5BByxhvVg94z0ETI8Yz3q9JmTwV5YulQgtIuOqzQdguZS/9gy2z4LeCtwPQGBAoi+m/ADHukEIkMYk=
before_install: 
jobs:
  include:
  - stage: build
    script:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASS"
    - docker build -t yael -f docker/yael.Dockerfile .
    - docker tag yael $DOCKER_USERNAME/yael
    - docker push $DOCKER_USERNAME/yael
