sudo: required
language: cpp
services:
- docker
cache:
  directories:
  - "$CACHE_DIR"
env:
  global:
  - CACHE_DIR=$HOME/.cache/docker
  - CACHE_FILE_YAEL=$CACHE_DIR/yael
  - secure: KSa2QlthvI+/xHpR1cIQUwyz9KxVtb/waBMgq0iPaezG+3iKdgIEGkCMvb144389nqIpBTSrnvLM27U90HbyzB6HJhkVf7nOZhWsGDVHZENWjau1u/N1jGdZGBh/odA0o94VfTHATT/+Ez8wf6Pd5gGNl8Az0EA0qKBEHMEqGH7ZcGBF9dfgz/Sr0IhCl+lDGFt8iMap2qs8xYUvPtajVmtA1en7Ja+NykpqJLwfdsXUHINdo7dwyCdqzC4VyX1Zq584DNVXdjyiPL28SmbVjH1Z5oTfg+r1p79cx2CdkW4QhSgUGtvtyG15IiaQrcDJsN9hokjH+RCZ2TTBm5fhl36PmmuxmC4OsLWnLDKnlDwhJid5ufABjrnaTsnFO+FYdxQwU+GHDYtOPjgXYu++rgDuVzRb2tAnJC598NRYVLeoAszcX6ZjNYVQZDClLuJDgr8gT66zmpKrFjn9QsPgIvHXkkrOWxFwPbTHBkazENnXrvT0OZtu4fy+eYwPnsc/xeifrs91ojzD8nKcmNZQwkL2Gtat5PFhOGG6uBFsLQcB1XKwdauxAshuNv8QcPveQNAbfFEN5FSkxXDCw1tFZdrCC90YrSke3bpc8WBTv0kGPALdnqy1DFTooZbRx1YVEVV5KorTSBRz7pzKu9J/aYJLvImLRic35+qZkl8Ripk=
  - secure: ALQBEr1ckAq7s8dc5bVwsE+Li0zvT3jzOY8vLotBEGQ7PqV8tvIrGUFu/VYVVBzs3XS/1a/xm5cw8rbP6P1fR6wSjyvjVc28WodTS+/s9PK9XynIXXMQr6kLI4rFgRDmj7/wmn1tsC0eExMeH20ku5VjpoU5VkQCdcedGbIP9Zp5cmaIxFRwsFamsAMQc05Nz0mEPTJURhEoNTZcFakyAQ1ZOLyeHsafeH0vysFqRBCsRI9UmddDxsEVt2cFR2QWLWJ0EemS5GRx67ME04qH1iulYeMd+XHHEnotvOJe/0DDWANYt4RUW9AGS/zDil399TD0QGtSgGgg0CZKlM81Nb8GQwuWyDBTZq/BkonCHOLNdxD0e5HkLue9PL9AynjmBcnikNzFonz1tQDqv47zHgB2JMm9ex3Hr5tVwONNRg/rOYH2i4p2+acPXa6DH4r6/LQNwjQwr/vYX6bay07gxo6/yfO5EzNqACSRiDHafHIJ8KAAt05KXYAdxgNDqINzzlznKxYiX9AD8KeCp9I8dGpMCtMwd6UQiimxc5qgNOMevIPb/DylTdVBz76VKwV4SNzLotgsocjeQyIIgPkpH5X5ccIXWCUHUAJQ7oDxlie4/9PG0WXojNVnABE5268+y73i43VIoujoXY9J4re0cKNrNZn2K7EY4JgCwP5SDJI=
before_install: 
jobs:
  include:
  - stage: build
    script:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASS"
    - docker build -t yael -f docker/yael.Dockerfile .
    - docker tag yael $DOCKER_USERNAME/yael
    - docker push $DOCKER_USERNAME/yael
  - stage: test
    script:
    - docker pull $DOCKER_USERNAME/yael
    - docker tag $DOCKER_USERNAME/yael yael
    - docker run --rm -it yael ../docker/run-clang-tidy.sh
  - stage: test
    script:
    - docker pull $DOCKER_USERNAME/yael
    - docker tag $DOCKER_USERNAME/yael yael
    - docker run --rm -it -e run_test=unit_test yael ../docker/run-test.sh
    - docker run --rm -it -e run_test=multi_client yael ../docker/run-test.sh
    - docker run --rm -it -e run_test=multi_client_delayed yael ../docker/run-test.sh
