name: Continuous Integration 

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
           submodules: recursive
      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install meson build-essential git g++ libgtest-dev libgflags-dev libboost-program-options-dev
            sudo apt-get install libpython3-dev libboost-python-dev pkg-config python3-pytest cmake clang
            sudo apt-get install libbotan-2-dev libgmp-dev libssl-dev libunwind-dev libgoogle-glog-dev -y
      - name: Build yael
        run: |
            meson build -Dbuildtype=release --prefix=$HOME/local
            cd build
            ninja -v
            ninja install -v
      - name: Lint Checks 
        run: cd build && ninja lint 
      - name: Unit Tests
        timeout-minutes: 5
        run: cd build && GLOG_v=3 ninja unit-tests
      - name: Integration Tests
        timeout-minutes: 15
        run: cd build && ninja integration-tests
